language: python
matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls